apiVersion: v1
kind: ConfigMap
metadata:
  name: go-service-config
  namespace: default
  labels:
    app: go-service
data:
  SERVER_PORT: "8080"
  REDIS_ADDR: "redis-master:6379"
  REDIS_PASSWORD: ""
  WINDOW_SIZE: "50"
  ANOMALY_ZSCORE: "2.0"

